#!/bin/sh

start() {
    mkdir -p /home/lava/printer_data/config/klipper
    mkdir -p /home/lava/printer_data/config/moonraker
    touch /home/lava/printer_data/config/klipper/00_keep.cfg
    touch /home/lava/printer_data/config/moonraker/00_keep.cfg
    chown -R lava:lava /home/lava/printer_data/config
}

stop() {
    true
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
