#!/bin/sh

start() {
    if [ -f /mnt/udisk/extended-recover.txt ]; then
        EXTENDED_DIR="/home/lava/printer_data/config/extended"

        # Move existing extended config to a backup location
        # find the next available backup number
        if [ -d "$EXTENDED_DIR" ]; then
            BACKUP_NUM=1
            while [ -d "$EXTENDED_DIR.backup.$BACKUP_NUM" ]; do
                BACKUP_NUM=$((BACKUP_NUM + 1))
            done
            mv "$EXTENDED_DIR" "$EXTENDED_DIR.backup.$BACKUP_NUM"
        fi
        rm -f /mnt/udisk/extended-recover.txt
    fi

    mkdir -p /home/lava/printer_data/config
    cp -rn /home/lava/default-config/. /home/lava/printer_data/config/
    chown -R lava:lava /home/lava/printer_data/config
}

case "$1" in
    start)
        start
        ;;
    stop)
        ;;
    restart|reload)
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
